### ISSUE TITLE
Week 3 Oct - 9 Oct

### ISSUE THREAD

**Issue by octref** [octref/vscode#4]

**Comment by Tyriar** [comment]
So the problem we discussed today was when `TreeContentProvider.resolveChildren(node: ITreeNode)` is called, how does the extension identify `node` from within the tree? We discussed the following members on ITreeNodeoptions:

- `id: number`: This would not be the best since `id` is just some arbitrary unique number from the extension's point of view.
- `equals(other: ITreeNode): boolean`: This would not solve the issue as the extension does not have a reference to the node as the return value from `TreeContentProvider.provideTreeContent` is used to construct another object.
- `data: any`: Allowing each tree node to keep some data object would solve the issue, it would also open a lot of doors some of which we may not want to open as well as require the extension author to fill it in to be able to unique ID the nodes. Let's reconsider this when there is a solid use case.
- `parent: ITreeNode`: This enables the extension to precisely identify the node within a tree, even down to the index of the child by calling into `ITreeNode.parent.children.indexOf` if needed. Let's add this to the API.

Tasks for this week:

- [ ] Add `ITreeNode.uri` (let's get it functional first!)
- [ ] Create and persist the tree on the extension host side then synchronize it with a copy on the main thread. The tree on the extension host side will always be kept up to date so it can provide each node's parent (`ITreeNode.parent`) in real time.
- [ ] Add `ITreeNode.parent`
- [ ] Add some tests
- [ ] Discuss approach with wider team
- [ ] PR to Microsoft/vscode
- [ ] Add `ITreeNode.iconUri`

**Comment by octref** [comment]
- [ ] Remove isChildrenResolved

**Comment by Tyriar** [comment]
Here's a concrete example of why we need `ITreeNode.parent` in order to identify the node within the tree. Say you implement an outline view for C#, the structure of the file looks like this:

- `class A`
  - `class B`
    - `class A`

How do you distinguish either `class A` when `resolveChildren(ITreeNode)` is called?

**Comment by octref** [comment]
As per today's discussion:

Actionable items:

- [ ] rename `isExpanded` to something like `shouldInitiallyExpand` to avoid confusion
- [ ] As `provideTreeContent` only provides root of tree, should be named like `provideTreeRoot`
- [ ] remove `children` from `TreeContentNode`'s interface. Instead make it provided by `resolveChildren`
- [ ] Make Provider generic
- [ ] and functions like `getLabel(node: T)` to `TreeContentNode`'s interface.

**Comment by octref** [comment]
### Thoughts on onclick Uri:

- Uri doesn't prevent user from doing whatever he wants if he can make a custom `ContentProvider` that registers for a special scheme.
- User might want to fire custom action (like executing a CLI command) when node get clicked
- User might not want to open any editor/webpage when node get clicked
- Need to worry conflict of schemes
- What if later we want to support right-click, double click, Enter key, etc?

--- 

### As for the reusability argument
  - If I'm writing an ext I wouldn't trust other providers
  - Creates dependency. For example, what if A depends on B's provider which uses libgit 2.0, but B upgrades to libgit 3.0?

So overall I'm not really for it, unless there are benefits that largely overweights these downsides.

**Comment by octref** [comment]
A similar API is CodeLens:

```ts
declare namespace vscode {
  registerCodeLensProvider(selector: DocumentSelector, provider: CodeLensProvider): Disposable;
  registerCommand(command: string, callback: (args: any[]) => any, thisArg?: any): Disposable;
  export class CodeLens {
    range: Range;
    command: Command;
    isResolved: boolean;
  }
  export interface Command {
    title: string;
    command: string;
    arguments?: any[];
  }
}
```

Users could register a command that does whatever he wants when a CodeLens is clicked.

An example, [vscode-gitlens](https://github.com/eamodio/vscode-gitlens)

![](https://raw.githubusercontent.com/eamodio/vscode-git-codelens/master/images/preview-gitlens.gif)

Can we do something similar by adding a string `leftClickCommand` to `TreeNode` interface?

**Comment by octref** [comment]
A `command: Command` property is on `CodeLens`, `CompletionItem` and `StatusBarItem`.

```ts
export interface Command {
  title: string;
  command: string;
  arguments?: any[];
}
```
which is fired after clicking `CodeLens` or `StatusBarItem`, or confirming a `CompletionItem`.

User can register command in this form

```ts
registerCommand(command: string, callback: (args: any[]) => any, thisArg?: any): Disposable;
```

I think we should follow this convention.

**Comment by octref** [comment]
- [ ] Update doc for TreeContentNode
- [ ] Flexbility example for  `TreeContentNode` `onClickCommand`.
